# **Reinforcement Learning: Taller 4**
## Estudiantes: Juan Pablo Reyes Fajardo y Santiago Rodríguez Ávila 

In [2]:
!pip install gym

In [1]:
import gym
import numpy as np

In [101]:
env = gym.make('CartPole-v1',render_mode="human")
cart_high_var = env.observation_space.high
cart_low_var = env.observation_space.low

def num_states(num):
    # dependiendo el numero de estados, cambia el tamaño de cada vector
    if num ==400:
        car_pos = np.linspace(cart_low_var[0], cart_high_var[0], num= 5)
        car_vel = np.linspace(-12, 12, num= 4)
        pole_angle = np.linspace(cart_low_var[2], cart_high_var[2], num = 5)
        pole_vel = np.linspace(-12, 12, num= 4)
    elif num ==4000:
        car_pos = np.linspace(cart_low_var[0], cart_high_var[0], num= 8)
        car_vel = np.linspace(-12, 12, num= 8)
        pole_angle = np.linspace(cart_low_var[2], cart_high_var[2], num = 8)
        pole_vel = np.linspace(-12, 12, num= 8)   
    # vector donde estan todos los valores que se pueden colocar en una tabla
    discrete_values = [car_pos, car_vel, pole_angle, pole_vel]
    return discrete_values


discrete_values = num_states(400)
Q_table = {}
states=[]
def set_states():
    for cpos in discrete_values[0]:
        for cvel in discrete_values[1]:
            for pang in discrete_values[2]:
                for pvel in discrete_values[3]:
                    states.append((cpos, cvel, pang, pvel))
                    
def set_q_table():
    for i in states:
        Q_table[i,action] = 0
    
                    
def discretize(new_state):
    # car pos, car vel, pole angle, pole vel
    valor_cercano=[0]*4
    for i in range(4):
        dif = [(abs(x - new_state[i])) for x in discrete_values[i]]
        valor_cercano[i] = discrete_values[i][dif.index(min(dif))]
        
    return valor_cercano
    

In [107]:
set_q_table()

a=discretize([-3.9,-9,0.3,-9])
print(a,'*'*8)
#Q_table[tuple(a),0]
#print(len(states))
for a in Q_table:
    print(a)

#-4.800000190734863, -12.0, 0.20943951606750488, -12.0

[-4.800000190734863, -12.0, 0.20943951606750488, -12.0] ********
((-4.800000190734863, -12.0, -0.41887903213500977, -12.0), 1)
((-4.800000190734863, -12.0, -0.41887903213500977, -4.0), 1)
((-4.800000190734863, -12.0, -0.41887903213500977, 4.0), 1)
((-4.800000190734863, -12.0, -0.41887903213500977, 12.0), 1)
((-4.800000190734863, -12.0, -0.20943951606750488, -12.0), 1)
((-4.800000190734863, -12.0, -0.20943951606750488, -4.0), 1)
((-4.800000190734863, -12.0, -0.20943951606750488, 4.0), 1)
((-4.800000190734863, -12.0, -0.20943951606750488, 12.0), 1)
((-4.800000190734863, -12.0, 0.0, -12.0), 1)
((-4.800000190734863, -12.0, 0.0, -4.0), 1)
((-4.800000190734863, -12.0, 0.0, 4.0), 1)
((-4.800000190734863, -12.0, 0.0, 12.0), 1)
((-4.800000190734863, -12.0, 0.20943951606750488, -12.0), 1)
((-4.800000190734863, -12.0, 0.20943951606750488, -4.0), 1)
((-4.800000190734863, -12.0, 0.20943951606750488, 4.0), 1)
((-4.800000190734863, -12.0, 0.20943951606750488, 12.0), 1)
((-4.800000190734863, -12.0, 0.

In [105]:
set_states()
len(states)
states

{((-4.800000190734863, -12.0, -0.41887903213500977, -12.0), 1): 0, ((-4.800000190734863, -12.0, -0.41887903213500977, -4.0), 1): 0, ((-4.800000190734863, -12.0, -0.41887903213500977, 4.0), 1): 0, ((-4.800000190734863, -12.0, -0.41887903213500977, 12.0), 1): 0, ((-4.800000190734863, -12.0, -0.20943951606750488, -12.0), 1): 0, ((-4.800000190734863, -12.0, -0.20943951606750488, -4.0), 1): 0, ((-4.800000190734863, -12.0, -0.20943951606750488, 4.0), 1): 0, ((-4.800000190734863, -12.0, -0.20943951606750488, 12.0), 1): 0, ((-4.800000190734863, -12.0, 0.0, -12.0), 1): 0, ((-4.800000190734863, -12.0, 0.0, -4.0), 1): 0, ((-4.800000190734863, -12.0, 0.0, 4.0), 1): 0, ((-4.800000190734863, -12.0, 0.0, 12.0), 1): 0, ((-4.800000190734863, -12.0, 0.20943951606750488, -12.0), 1): 0, ((-4.800000190734863, -12.0, 0.20943951606750488, -4.0), 1): 0, ((-4.800000190734863, -12.0, 0.20943951606750488, 4.0), 1): 0, ((-4.800000190734863, -12.0, 0.20943951606750488, 12.0), 1): 0, ((-4.800000190734863, -12.0, 0.

[(-4.800000190734863, -12.0, -0.41887903213500977, -12.0),
 (-4.800000190734863, -12.0, -0.41887903213500977, -4.0),
 (-4.800000190734863, -12.0, -0.41887903213500977, 4.0),
 (-4.800000190734863, -12.0, -0.41887903213500977, 12.0),
 (-4.800000190734863, -12.0, -0.20943951606750488, -12.0),
 (-4.800000190734863, -12.0, -0.20943951606750488, -4.0),
 (-4.800000190734863, -12.0, -0.20943951606750488, 4.0),
 (-4.800000190734863, -12.0, -0.20943951606750488, 12.0),
 (-4.800000190734863, -12.0, 0.0, -12.0),
 (-4.800000190734863, -12.0, 0.0, -4.0),
 (-4.800000190734863, -12.0, 0.0, 4.0),
 (-4.800000190734863, -12.0, 0.0, 12.0),
 (-4.800000190734863, -12.0, 0.20943951606750488, -12.0),
 (-4.800000190734863, -12.0, 0.20943951606750488, -4.0),
 (-4.800000190734863, -12.0, 0.20943951606750488, 4.0),
 (-4.800000190734863, -12.0, 0.20943951606750488, 12.0),
 (-4.800000190734863, -12.0, 0.41887903213500977, -12.0),
 (-4.800000190734863, -12.0, 0.41887903213500977, -4.0),
 (-4.800000190734863, -12.0, 

In [18]:
env.reset()
max_val = [0]*4
for i in range(500):
    action = env.action_space.sample()
    new_state, reward, done, _,_=env.step(action)
    cont =0
    for a in max_val:
        if new_state[cont]>= a:
            max_val[cont]=new_state[cont]
        cont+=1
    #print(new_state)
#print(max_val)
    #env.render()

error: display Surface quit

In [17]:
env.close()

In [41]:
env = gym.make('CartPole-v1')
# Initialize Q-table
Q = np.zeros([env.observation_space.shape[0], env.action_space.n])
print(Q)
# Set learning parameters
alpha = 0.8
gamma = 0.95
epsilon = 0.1

# Initialize variables
num_episodes = 5000
max_steps_per_episode = 200
rewards = []

# Q-learning algorithm
for i in range(num_episodes):
    state = env.reset()
    episode_reward = 0
    for j in range(max_steps_per_episode):
        # Choose action greedily with noise
        if np.random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()
        else:
            print(state[0],"-"*10)
            action = np.argmax(Q[state[0], :])
        # Get new state and reward from environment
        new_state, reward, done, _,_= env.step(action)
        print(new_state)
        # Update Q-table
        print(Q.shape,"*"*8)
        Q[state, action] = (1 - alpha) * Q[state, action] + alpha * (reward + gamma * np.max(Q[new_state, :]))
        episode_reward += reward
        state = new_state
        if done:
            break
    rewards.append(episode_reward)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[ 0.01770938 -0.04138917 -0.03702587 -0.01934518] ----------


IndexError: arrays used as indices must be of integer (or boolean) type

In [27]:
prueba = np.zeros([4,2])
prueba[0,1]= 2
prueba[1,0]= 4
prueba[2,0]= 1
prueba[3,1]= 8

state = env.reset()

print(state[0])
#print(env.observation_space)
#env.observation_space.low[2]
#prueba[state,0]
#print(prueba)
#print(prueba[1,:])
#np.argmax(prueba[0,:])

[-0.02061262 -0.00248625  0.00048967 -0.04600552]


In [73]:
cont = 0
Q_table = {}
for cpos in discrete_values[0]:
        for cvel in discrete_values[1]:
            for pang in discrete_values[2]:
                for pvel in discrete_values[3]:
                    for action in range(2):
                        Q_table[(cpos, cvel, pang, pvel),action] = 0
                        cont+=1
print(cont)
#Q_table

800


In [77]:
a=[]
a.append((1,2))
a.append((1,2,3,4))
a

[(1, 2), (1, 2, 3, 4)]