# **Reinforcement Learning: Taller 4**
## Estudiantes: Juan Pablo Reyes Fajardo y Santiago Rodríguez Ávila 

In [2]:
!pip install gym

In [3]:
import gym
import numpy as np

In [14]:
env = gym.make('CartPole-v1',render_mode="human")
cart_high_var = env.observation_space.high
cart_low_var = env.observation_space.low

def num_states(num):
    # dependiendo el numero de estados, cambia el tamaño de cada vector
    if num ==400:
        car_pos = np.linspace(cart_low_var[0], cart_high_var[0], num= 5)
        car_vel = np.linspace(-2, 2, num= 4)
        pole_angle = np.linspace(cart_low_var[2], cart_high_var[2], num = 5)
        pole_vel = np.linspace(-2, 2, num= 4)
    elif num ==4000:
        car_pos = np.linspace(cart_low_var[0], cart_high_var[0], num= 8)
        car_vel = np.linspace(-2, 2, num= 8)
        pole_angle = np.linspace(cart_low_var[2], cart_high_var[2], num = 8)
        pole_vel = np.linspace(-2, 2, num= 8)   
    # vector donde estan todos los valores que se pueden colocar en una tabla
    discrete_values = [car_pos, car_vel, pole_angle, pole_vel]
    return discrete_values


discrete_values = num_states(400)
Q_table = {}
states=[]
def set_states():
    for cpos in discrete_values[0]:
        for cvel in discrete_values[1]:
            for pang in discrete_values[2]:
                for pvel in discrete_values[3]:
                    states.append((cpos, cvel, pang, pvel))
                    
def set_q_table():
    for i in states:
        for action in range(2):
            Q_table[i,action] = 0
    
                    
def discretize(new_state):
    # car pos, car vel, pole angle, pole vel
    valor_cercano=[0]*4
    for i in range(4):
        dif = [(abs(x - new_state[i])) for x in discrete_values[i]]
        valor_cercano[i] = discrete_values[i][dif.index(min(dif))]
        
    return valor_cercano

In [3]:
#SARSA algorithm
def SARSA_algorithm(num_episodes):
    allowed_actions=[0,1]
    # Variables: alpha, gamma y epsilon.
    alpha = 0.3
    gamma = 1
    epsilon = 0.1
    cont = 0
    #Para 5000 episodios de entrenamiento
    for i in range(num_episodes):
        # Inicializa las variables para cada episodio
        state=env.reset()
        num_steps = 0
        state = discretize(state[0])


        # Seleccion accion "a" de forma epsilon-greedy
        if epsilon< np.random.uniform():        
            act_arg = np.array([Q_table[tuple(state), act] for act in range(2)])
            action = allowed_actions[np.argmax(act_arg)]
        else:
            action = env.action_space.sample()

        # Inicia el episodio
        continue_episode = True
        while continue_episode:        
            # Obtengo s'
            new_state, reward, done, _,_=env.step(action)
            new_state = discretize(new_state)

            # Revisa que new_state no sea un estado terminal
            if done:
                # Valor q(s',a') terminal
                q_value_next_step = 0
            else:
                #Obtengo a' de s' con epsilon greedy
                if epsilon< np.random.uniform():        
                    act_arg = np.array([Q_table[tuple(state), act] for act in range(2)])
                    new_action = allowed_actions[np.argmax(act_arg)]
                else:
                    new_action = env.action_space.sample()

                # Valor q(s',a') no terminal
                q_value_next_step = Q_table[tuple(new_state),new_action]


            # Calculo de actualizacion q(s,a) <- q(s,a) + alpha*(R + gamma*q(s',a') - q(s,a))
            Q_table[tuple(state), action] += alpha*(reward + gamma*q_value_next_step - Q_table[tuple(state),action])

            # asigna a = a' y s = s'
            state = new_state
            action = new_action


            # Parte que termina el episodio si se llega a algun estado terminal
            if done:
                continue_episode = False
        cont+=1
        if cont%100==0:
            print(cont)

## SARSA con 400 estados:

In [16]:
set_states()
set_q_table()

In [17]:
discrete_values = num_states(400)
SARSA_algorithm(5000)

C:\Users\Santiago\miniconda3\lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000


In [18]:
allowed_actions= [0,1]
prom=[]
prom_rand=[]
for i in range(100):
    G_pi = 0
    state =env.reset()
    state = state[0]
    state = discretize(state)
    act_arg = np.array([Q_table[tuple(state), act] for act in range(2)])
    action = allowed_actions[np.argmax(act_arg)]
    done = False
    n=1
    while not done:
        new_state, reward, done, _,_=env.step(action)
        G_pi= G_pi + reward
        discrete_state = discretize(new_state)
        act_arg = np.array([Q_table[tuple(discrete_state), act] for act in range(2)])
        action = allowed_actions[np.argmax(act_arg)]
    prom.append(G_pi)
print('---'*5)
for i in range(100):
    G_pi = 0
    state =env.reset()
    done = False
    while not done:
        action = env.action_space.sample()
        new_state, reward, done, _,_=env.step(action)
        G_pi= G_pi + reward
    prom_rand.append(G_pi)

In [19]:
print("Retorno obtenido con la funcion q:",sum(prom)/len(prom))
print("Retorno obtenido de acciones al azar:",sum(prom_rand)/len(prom_rand))

Retorno obtenido con la funcion q: 189.28
Retorno obtenido de acciones al azar: 21.97


## SARSA con 4000 estados:

In [4]:
set_states()
set_q_table()

In [7]:
discrete_values = num_states(4000)
SARSA_algorithm(1000)

C:\Users\Santiago\miniconda3\lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


100
200
300
400
500
600
700
800
900
1000


In [11]:
prom=[]
prom_rand=[]
allowed_actions= [0,1]
for i in range(100):
    G_pi = 0
    state =env.reset()
    state = state[0]
    state = discretize(state)
    act_arg = np.array([Q_table[tuple(state), act] for act in range(2)])
    action = allowed_actions[np.argmax(act_arg)]
    done = False
    n=1
    while not done:
        new_state, reward, done, _,_=env.step(action)
        G_pi= G_pi + reward
        discrete_state = discretize(new_state)
        act_arg = np.array([Q_table[tuple(discrete_state), act] for act in range(2)])
        action = allowed_actions[np.argmax(act_arg)]
    prom.append(G_pi)
print('---'*5)
for i in range(100):
    G_pi = 0
    state =env.reset()
    done = False
    while not done:
        action = env.action_space.sample()
        new_state, reward, done, _,_=env.step(action)
        G_pi= G_pi + reward
    prom_rand.append(G_pi)

---------------


In [12]:
print("Retorno obtenido con la funcion q:",sum(prom)/len(prom))
print("Retorno obtenido de acciones al azar:",sum(prom_rand)/len(prom_rand))

Retorno obtenido con la funcion q: 218.33
Retorno obtenido de acciones al azar: 21.88


In [20]:
env.close()

## Uso de redes neuronales

In [12]:
import random
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
'''
# Define the hyperparameters
EPISODES = 5000
EPSILON = 1.0
EPSILON_MIN = 0.01
EPSILON_DECAY = 0.999
GAMMA = 0.99
ALPHA = 0.001
BATCH_SIZE = 32

# Define the environment
env = gym.make('CartPole-v1')

# Define the model
model = Sequential()
model.add(Dense(4, input_dim=4, activation='relu'))
model.add(Dense(2, activation='linear'))
model.compile(loss='mse', optimizer='adam')
'''



class DSARSAAgent:
    def __init__(self, state_dim, action_dim, learning_rate=0.001, discount_factor=0.99, epsilon=1.0, epsilon_decay=0.999):
        self.state_dim = state_dim
        self.action_dim = action_dim
        self.learning_rate = learning_rate
        self.discount_factor = discount_factor
        self.epsilon = epsilon
        self.epsilon_decay = epsilon_decay
        self.model = self.build_model()

    def build_model(self):
        model = Sequential()
        model.add(Dense(4, input_dim=self.state_dim, activation='relu'))
        model.add(Dense(2, activation='linear'))
        model.compile(loss='mse', optimizer='adam')
        print(model.summary())
        return model

    def choose_action(self, state):
        if np.random.rand() <= self.epsilon:
            return np.random.choice(self.action_dim)
        q_values = self.model.predict(state)
        return np.argmax(q_values[0])

    def update_model(self, state, action, reward, next_state, next_action, done):
        target = reward
        if not done:
            target += self.discount_factor * self.model.predict(next_state)[0][next_action]
        target_f = self.model.predict(state)
        target_f[0][action] = target
        self.model.fit(state, target_f, epochs=1, verbose=0)

In [13]:
env = gym.make('CartPole-v1',render_mode="human")
num_episodes=100
# Define your state and action dimensions
state_dim = 4
action_dim = 2

# Create an instance of the DSARSAAgent class
agent = DSARSAAgent(state_dim, action_dim)
for episode in range(num_episodes):
    state = env.reset()
    state = state[0]
    done = False
    total_reward = 0

    while not done:
        # Choose an action
        action = agent.choose_action(state)

        # Take the chosen action and observe the next state and reward
        next_state, reward, done, _,_ = env.step(action)
        next_state = np.reshape(next_state, [1, state_dim])

        # Choose the next action
        next_action = agent.choose_action(next_state)

        # Update the model
        agent.update_model(state, action, reward, next_state, next_action, done)

        # Update the current state
        state = next_state
        total_reward += rewardsummary

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_14 (Dense)            (None, 4)                 20        
                                                                 
 dense_15 (Dense)            (None, 2)                 10        
                                                                 
Total params: 30
Trainable params: 30
Non-trainable params: 0
_________________________________________________________________
None
1/1 [==============================] - 0s 362ms/step


InvalidArgumentError: Graph execution error:

Detected at node 'sequential_7/dense_14/MatMul' defined at (most recent call last):
    File "C:\Users\Santiago\miniconda3\lib\runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Users\Santiago\miniconda3\lib\runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "C:\Users\Santiago\AppData\Roaming\Python\Python310\site-packages\traitlets\config\application.py", line 1043, in launch_instance
      app.start()
    File "C:\Users\Santiago\miniconda3\lib\site-packages\ipykernel\kernelapp.py", line 724, in start
      self.io_loop.start()
    File "C:\Users\Santiago\AppData\Roaming\Python\Python310\site-packages\tornado\platform\asyncio.py", line 215, in start
      self.asyncio_loop.run_forever()
    File "C:\Users\Santiago\miniconda3\lib\asyncio\base_events.py", line 603, in run_forever
      self._run_once()
    File "C:\Users\Santiago\miniconda3\lib\asyncio\base_events.py", line 1899, in _run_once
      handle._run()
    File "C:\Users\Santiago\miniconda3\lib\asyncio\events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\ipykernel\kernelbase.py", line 512, in dispatch_queue
      await self.process_one()
    File "C:\Users\Santiago\miniconda3\lib\site-packages\ipykernel\kernelbase.py", line 501, in process_one
      await dispatch(*args)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\ipykernel\kernelbase.py", line 408, in dispatch_shell
      await result
    File "C:\Users\Santiago\miniconda3\lib\site-packages\ipykernel\kernelbase.py", line 731, in execute_request
      reply_content = await reply_content
    File "C:\Users\Santiago\miniconda3\lib\site-packages\ipykernel\ipkernel.py", line 417, in do_execute
      res = shell.run_cell(
    File "C:\Users\Santiago\miniconda3\lib\site-packages\ipykernel\zmqshell.py", line 540, in run_cell
      return super().run_cell(*args, **kwargs)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2945, in run_cell
      result = self._run_cell(
    File "C:\Users\Santiago\miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3000, in _run_cell
      return runner(coro)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3203, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "C:\Users\Santiago\miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3382, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "C:\Users\Santiago\miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3442, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\Santiago\AppData\Local\Temp\ipykernel_15796\300310841.py", line 27, in <module>
      agent.update_model(state, action, reward, next_state, next_action, done)
    File "C:\Users\Santiago\AppData\Local\Temp\ipykernel_15796\1772366920.py", line 55, in update_model
      target_f = self.model.predict(state)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\keras\engine\training.py", line 2382, in predict
      tmp_batch_outputs = self.predict_function(iterator)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\keras\engine\training.py", line 2169, in predict_function
      return step_function(self, iterator)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\keras\engine\training.py", line 2155, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Santiago\miniconda3\lib\site-packages\keras\engine\training.py", line 2143, in run_step
      outputs = model.predict_step(data)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\keras\engine\training.py", line 2111, in predict_step
      return self(x, training=False)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\keras\engine\training.py", line 558, in __call__
      return super().__call__(*args, **kwargs)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\keras\engine\base_layer.py", line 1145, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\keras\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\keras\engine\sequential.py", line 412, in call
      return super().call(inputs, training=training, mask=mask)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\keras\engine\functional.py", line 512, in call
      return self._run_internal_graph(inputs, training=training, mask=mask)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\keras\engine\functional.py", line 669, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\keras\engine\base_layer.py", line 1145, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\keras\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\Santiago\miniconda3\lib\site-packages\keras\layers\core\dense.py", line 241, in call
      outputs = tf.matmul(a=inputs, b=self.kernel)
Node: 'sequential_7/dense_14/MatMul'
In[0] ndims must be >= 2: 1
	 [[{{node sequential_7/dense_14/MatMul}}]] [Op:__inference_predict_function_1277]

In [14]:
env.close()

In [16]:
EPISODES = 5000
EPSILON = 1.0
EPSILON_MIN = 0.01
EPSILON_DECAY = 0.999
GAMMA = 0.99
ALPHA = 0.001
BATCH_SIZE = 32

# Define the environment
env = gym.make('CartPole-v1')

# Define the model
model = Sequential()
model.add(Dense(4, input_dim=4, activation='relu'))
model.add(Dense(2, activation='linear'))
model.compile(loss='mse', optimizer='adam')
weights=model.get_weights()
for i, layer_weights in enumerate(weights):
    print(f"Capa {i + 1} - Pesos:")
    print(layer_weights)
    print()

Capa 1 - Pesos:
[[-0.7432852  -0.1486429  -0.1371448   0.24629325]
 [ 0.3666528   0.39687043  0.17363995 -0.03056824]
 [ 0.11689937  0.46246618 -0.45954245  0.03358054]
 [ 0.5355603   0.2761702   0.713564    0.04761124]]

Capa 2 - Pesos:
[0. 0. 0. 0.]

Capa 3 - Pesos:
[[-0.8054986  -0.3941636 ]
 [ 0.271904   -0.06075954]
 [-0.00227332  0.3381405 ]
 [-0.28135157  0.73801684]]

Capa 4 - Pesos:
[0. 0.]

